### ISSUE TITLE
Create MyAccount Component

### ISSUE THREAD

**Issue by rscottlundgren** [arc-hive-network/hive-front-end#16]
Create the component for the MyAccount page and connect it with the overarching framework of the site. 

Do not forget to include it in the NavBar.

**Comment by mxkay** [comment]
Created the MyAccount component and connected it to the appropriate Route. Added basic ability to view and edit user info (name, handle, pronouns, email, phone). To fully implement, we will need to decide where user information is being stored, and we will need to create and pass an external function for updating the user information after the form submits.
