### ISSUE TITLE
Create CellCreate Component

### ISSUE THREAD

**Issue by rscottlundgren** [arc-hive-network/hive-front-end#17]
Create the component for the CellCreate page and connect it with the overarching framework of the site. 

Do not forget to include it in the NavBar.

**Comment by ArKaneVision** [comment]
@Frankazo Should this be closed?

**Comment by Frankazo** [comment]
Related to https://github.com/arc-hive-network/hive-front-end/commit/3beb4456a083549bc0b6021aed410716cf97ed03
